import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import {
    Box,
    Breadcrumb,
    BreadcrumbItem,
    BreadcrumbLink,
} from "@chakra-ui/react";
import { useContext } from "react";
import { cookieContext } from "./cookieContext";
import CookieCounter from "./CookieCounter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <Box
                        display="flex"
                        flexDirection={"column"}
                        height={"100vh"}
                    >
                        <Box
                            bg="#eea9b8"
                            w="100%"
                            p={4}
                            color="white"
                            display="flex"
                        >
                            <CookieCounter />
                        </Box>

                        {children}
                        <Box
                            bg="#52280b"
                            w="100%"
                            p={4}
                            color="white"
                            display="flex"
                        >
                            Delicious Footer goes here...
                        </Box>
                    </Box>
                </Providers>
            </body>
        </html>
    );
}
